apiVersion: ccm.harness.io/v1
kind: AutoStoppingRule
metadata:
  # do not change this AutoStoppingRule name, as we need it for the jq engine
  name: autostopping-<PROJECT_NAME>-rule
  namespace: ccm-challenge
  annotations:
      # do not change this harness annotation
      harness.io/cloud-connector-id: dummyaws
spec:
    service:
        name: <SVC_NAME>
        port: 80
    ingress:
        name: <ING_NAME>
        controllerName: nginx
    idleTimeMins: 5
    hideProgressPage: false
